enactjs/dev-utils

- option-parser.js
> ENYO-5100: Fix resolution independence settings parsing/autodetection.

- plugins/SnapshotPlugin/index.js
- plugins/SnapshotPlugin/snapshot-helper.js
> ENYO-5191: Support snapshot utility for window callbacks

- plugins/PrerenderPlugin/index.js
> ENYO-5208: Preserve React15 HTML comment nodes within prerenders

- mixins/isomorphic.js
- option-parser.js
- package-lock.json
- plugins/PrerenderPlugin/README.md
- plugins/PrerenderPlugin/index.js
> ENYO-5238: Support non-inline startup js scripts in prerenders

- plugins/PrerenderPlugin/templates.js
> ENYO-5302: Support dynamic enact resolution class usage in prerendered html output.

- option-parser.js
> ENYO-5150: Expose accent value mappings for Spotlight customization.

- index.js
- mixins/index.js
- mixins/verbose.js
- plugins/VerboseLogPlugin/README.md
- plugins/VerboseLogPlugin/index.js
> ENYO-5310: Add vebose logging support to Enact CLI pack

- plugins/PrerenderPlugin/templates.js
> ENYO-5438: dynamic locale classes missing whitespace separator.

- plugins/PrerenderPlugin/templates.js
> ENYO-5440: locale class isn't applied if app uses deeplink feature

- mixins/unmangled.js
Had some config in place for an older version (I'm assuming) of the uglify-webpack-plugin.
Update to use the right config options
> ENYO-5645: Fix configuration of Uglify when not minifying

- package.json
Signed-off-by: Ryan Duffy <ryan.duffy@lge.com>
> PLAT-72795: Update React to 16.7

- option-parser.js
- plugins/ILibPlugin/index.js
Updates the iLibWebpackPlugin to support multiple theme packages, each with the own resbundle resources.
> PLAT-83210: Support non-moonstone themes in iLibWebpackPlugin

- plugins/SnapshotPlugin/index.js
Previously we would attempt to ignore certain packages (ilib, i18n, moonstone), when not found, for snapshotted apps. This would avoid errors in the snapshot-helper about missing modules.
However, the `ilib` test was being used in regex form on resource path and as a result all of `@enact/i18n/ilib` would be ignored if `ilib` package was absent. This would cause many issues, including failure of prerendering.
This fix uses `checkResource` filter function instead of regex and ensures the IgnorePlugin is only apply on SnapshotPlugin helper context. Additionally adds special handling for `ilib` to ensure `ilib` is only ignored when both `ilib` and `@enact/i18n/ilib` is missing (as we support aliases of both paths).
> PLAT-84731: Fix V8 snapshotting when ilib external package is not found

- plugins/ILibPlugin/index.js
Remove special moonstone handling and instead update the constant map to always include the active package. This allows all themes to have their own tests and resbundles without hacky workarounds.
> PLAT-99378: Update iLibWebpackPlugin to support ui/screenshot test structure

- plugins/ILibPlugin/index.js
Adds a `symlinks` option that mirrors the `symlinks` option in webpack. Controls whether or not to resolve symlink paths to true relative filesystem location. Defaults to `true` like webpack.
> PLAT-106664: Preserve unresolved symlinks path in output

- CHANGELOG.md
- plugins/SnapshotPlugin/snapshot-helper.js
This PR merges #65(released in 2.8.1) to develop.
> Merge #65 to develop

- CHANGELOG.md
- mixins/framework.js
This PR fixes wrong glob patterns for the test files.
> PLAT-138171: Fixed the glob pattern for ignoring test files

- plugins/ILibPlugin/README.md
- plugins/PrerenderPlugin/README.md
> PLAT-136430: Update docs

- CHANGELOG.md
- plugins/PrerenderPlugin/index.js
- plugins/PrerenderPlugin/templates.js
Clean up "data-react-checksum" related code
Removed react checksum related code
WRN-3542
> WRN-3542: Clean up "data-react-checksum" related code

- .eslintrc.js
- package.json
ESLint v8.0.0 is [released](https://eslint.org/blog/2021/10/eslint-v8.0.0-released) 🎉
Dependencies should be compatible with ESLint 8 too
update eslint 8 & related modules
**※ BEFORE THIS CHANGE, UPDATE & RELEASE WRN-12124 FIRST.**
WRN-12748
> WRN-12748: Update eslint 8 related modules

- plugins/SnapshotPlugin/README.md
Fixed some typos in the md 
Enact-DCO-1.0-Signed-off-by: Seungho Park <seunghoh.park@lge.com>
> Fix some typos

- mixins/verbose.js
- npm-shrinkwrap.json
- package.json
Fix a error when `enact pack --verbose`: https://github.com/enactjs/dev-utils/pull/125/commits/2b4aea35c7571e25a53f72af14a383dcc36cff3f
> $ enact pack --verbose
>Creating a development build...
>
>Failed to compile.
>
>Chalk is not a constructor
WRP-20604
> WRP-20604: Updated dependencies' minor version

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
`prettier` v3 and `eslint-plugin-prettier` v5 had been released.
This module needs to be updated to the latest node modules to fix security vulnerabilities and prevent malware.
Updates `prettier` related modules' version updates to the latest.
There are no breaking changes affecting this repository.
- https://prettier.io/blog/2023/07/05/3.0.0.html
- https://github.com/prettier/prettier/wiki/How-to-migrate-my-plugin-to-support-Prettier-v3%3F
[//]: # (Related issues, …
> WRP-21844: Updates prettier related modules' major version updates

- npm-shrinkwrap.json
- package.json
Updates prettier related modules' version updates to the latest.
There are no breaking changes affecting this repository.
WRP-21844
https://prettier.io/blog/2023/07/05/3.0.0.html
https://github.com/prettier/prettier/wiki/How-to-migrate-my-plugin-to-support-Prettier-v3%3F
WRP-21914
> WRP-21914: Updated dependencies' minor version

- CHANGELOG.md
- plugins/VerboseLogPlugin/index.js
VerboseLogPlugin contains recursive functions, it may fall into an infinite loop if there is no exception handling.
Add an exception handling on VerboseLogPlugin
WRP-27950
> WRP-27950: Add an exception handling on VerboseLogPlugin

- npm-shrinkwrap.json
- package.json
> WRQ-415: Update minor dependencies to fix vulnerabilities

- npm-shrinkwrap.json
- package.json
> WRQ-421: Update minor dependencies to fix vulnerabilities

- npm-shrinkwrap.json
- package.json
> WRQ-13128: Update minor dependencies to fix vulnerabilities

- npm-shrinkwrap.json
- package.json
Update react related modules to v19
Update react related modules to v19
WRQ-21653
> WRQ-21653: Update react related modules to v19

- npm-shrinkwrap.json
- package.json
Update dependencies' minor version
Update dependencies' minor version
WRQ-27221
> WRQ-27221: Update dependencies' minor version

- eslint.config.js
- npm-shrinkwrap.json
- package.json
We have already implemented eslint 9, and going forward, configs other than eslint.config.js (eslintrc files, eslintignore files, package.json, etc.) will no longer work.
Remove eslint-related configs in package.json
Remove eslint-config-enact-proxy module
WRR-22888
> WRR-22888: Remove eslint-related configs in package.json
