enactjs/dev-utils

- plugins/SnapshotPlugin/mock-window.js
Fixes the issue by using dynamic timer/console functions during `react-dom` modular evaluation. While evaluated in v8 snapshot, any execution will be a noop, however when the window exists, the real window-based function will execute. This is mainly for instances where the setTimeout or console functions are captured and assigned to local variables at a modular level within `react-dom`. In React 16.4.1, this is the case within the react scheduler section.
> ENYO-5358: snapshot build fails with react-dom 16.4.1

- plugins/PrerenderPlugin/vdom-server-render.js
To get correct path for fontGenerator, I wrapped opt.fontGenerator with path.resolve.
> Prerendering: can notice default font until locale class are added (1 QE)

- CHANGELOG.md
- plugins/WebOSMetaPlugin/index.js
- Most apps were removed from the home launcher. So, that apps don't have their splash images.
- Currently, default splash image displays in recent area of home launcher.
- GUI team want all applications to display their recent images instead of default splash image.
- The image file specified as 'imageForRecents' in appinfo.json file should be included in the build output.
- Add new `WebOSMetaPlugin` `imageForRecents` as prop.
> ENYO-5597: Added new WebOSMetaPlugin `imageForRecents`

- mixins/externals.js
- mixins/framework.js
- mixins/index.js
- mixins/isomorphic.js
- mixins/stats.js
- mixins/unmangled.js
- mixins/verbose.js
- plugins/dll/EnactFrameworkRefPlugin.js
Fixes designed to support https://github.com/enyojs/enact-ui-tests/pull/41
Issue:
* EnactFrameworkRefPlugin broken on Webpack 4. It, along with chainable config mixins are desired for https://github.com/enyojs/enact-ui-tests/pull/41
Resolution:
* Fix EnactFrameworkRefPlugin based off Webpack 4 dll format and the latest HtmlWebpackPlugin.
* Fixes dynamic setting `ILIB_BASE_PATH` for EnactFrameworkRefPlugin.
* Only hook in to webOS appinfo events when WebOSMetaWebpackPlugin is used.
* Removes `@enact/dev-utils` from the possible entrypoints that framework builds can use.
* All mixins now return the configs themselves, to support chaining.
> PLAT-68152: Improve Enact UI Test build speed

- option-parser.js
Adds support for `forceCSSModules` Enact build option which will be used by CLI to force all CSS/LESS to be handled in a modular context.
> PLAT-72905: Support forceCSSModules flag for modular CSS scope backwards compatibility

- mixins/isomorphic.js
- package.json
- plugins/PrerenderPlugin/README.md
- plugins/PrerenderPlugin/index.js
- plugins/PrerenderPlugin/vdom-server-render.js
Expose React and use it within the DOM server, rather than allowing a second copy to load via NodeJS at prerender-time.
* Modify PrerenderPlugin `server` option to be the path to the server module, rather than the evaluated object.
* Exposes `React` as a global for use by the PrerenderPlugin
* Reroute the `react-dom/server` to use the global `React` object if it exists for the instance, so it doesn't require a separate NodeJS-level copy.
> PLAT-78229: Fix prerendering for hook-based components

- plugins/WebOSMetaPlugin/index.js
Use `Buffer.from()` rather than `new Buffer()` for creating new Buffer objects from strings. Old format was was officially deprecated in NodeJS and gives an ugly console warning.
> PLAT-78457: Use non-deprecated Buffer initialization syntax

- option-parser.js
Extends browsers support matrix to explicitly state `'last 5 Chrome versions'` and `'last 5 Firefox versions'` since that made more sense than just the last 2 versions for those particular browsers with rapid release schedules.
> PLAT-78522: Redefine/clarify core Enact browserslist format

- package-lock.json
- package.json
Revert to find-cache-dir@^2.0.0 to retain Node 6.x support.
> PLAT-81140: Compatibility with Node 6.x for Enact CLI 2.x

- plugins/ILibPlugin/index.js
- plugins/PrerenderPlugin/FileXHR.js
- plugins/SnapshotPlugin/index.js
- plugins/SnapshotPlugin/snapshot-helper.js
- plugins/dll/EnactFrameworkRefPlugin.js
Transitions all former `@enact/i18n/ilib/...` references to use `ilib` npm package.  This includes modifying how we detect iLib location for the iLibPlugin, as well as how `ILIB_BASE_PATH` elsewhere within the dev-utils.  Additionally adds a ContextReplacementPlugin to quiet warnings from generated contexts within iLib which are not intended for web-based usage.
> PLAT-80499: Transition to external iLib NPM module

- option-parser.js
Before the default case when no `ri` was specified and no base screentype was detected was `{baseSize: null}`, which then results in bad math in the POSTCSS plugin.
Switching base-case to undefined/null allows the plugin to use its default values/settings. Special support handing for explicit `"ri": false` to disable resolution independence entirely.
> PLAT-81105: Undetermined RI value can result in Infinity rem values

- option-parser.js
- package-lock.json
- package.json
- plugins/ILibPlugin/index.js
Backward-compatible rewrite of the option parser for the `enact` object in `package.json`. Same option names, but with recursive/computed theme support. Will now support the following parse-order:
1. Environment variable level. Top level overriding in the form `ENACT_<OPTION>`.
2. App-level settings.  The normal options in an app's `enact` object in the `package.json`. Same options/values supported like before
3. Theme-level config.  The `theme` option in #2 will direct Enact dev-utils/CLI to read that package's `package.json` as well as auto-detect the presence of certain files (screentypes, fontgenerator). The adds the ability for theme packages to include their own settings, such as theme-specific html templates, resolution independence, etc..
Furthermore, themes can now extend other …
> PLAT-72711: Design and implement an Enact theme standard config

- option-parser.js
Adds support for auto-detecting local source level instances of `screenTypes.json` and `fontGenerator.js`.  This allows auto-detection for things like ui/screenshot tests and anything run within a theme repo itself.
> PLAT-101001: CLI: Add support for detecting local theme files

- plugins/ILibPlugin/index.js
* Adds support for `ILIB_ASSET_EMIT` env var to override iLib asset emit handling. When set 'false', will disable iLib asset emitting (no ilib locale data or theme/app resbundles will be copied to `./dist`).
* When `ilib` option/`ILIB_BASE_PATH` env var is not absolute, but `emit` option/`ILIB_ASSET_EMIT` env var is set false, then it is safe to assume no assets are desired for the app and a `ILIB_NO_ASSETS` constant is set accordingly. This is used by https://github.com/enactjs/enact/pull/2768 accordingly.
> ENYO-6436: Support disabling of ilib assets/loader

- CHANGELOG.md
- plugins/WebOSMetaPlugin/index.js
This adds support for packaging higher-resolution icon assets via the `extraLargeIcon` prop in `webOSMetaPlugin`.
> PLAT-113710: Add extraLargeIcon asset support to webOSMetaPlugin

- mixins/framework.js
* `framework` mixin: Adds the full list of Jest unit test locations to ignore when scanning framework files to include in framework bundles.
> PLAT-113570: Ignore full array of jest unit test locations

- plugins/dll/EnactFrameworkRefPlugin.js
* Ensures locally-accessed files within ignored packages do not get delegated.
> PLAT-115836: Screenshot tests don't build properly with cli 3.0

- mixins/externals.js
- mixins/framework.js
- plugins/ILibPlugin/README.md
- plugins/ILibPlugin/index.js
* `externals` and `framework` mixins: ensure that `@enact/i18n` is included with a framework bundle, even when local files. This package is unique as it contains the iLib path hardcoding and should be within the framework bundle.
* `framework` mixin: set relative application resbundle (`"resources"` relative to the html location)
* `ILibPlugin`:
* Add support for `relativeResources` boolean option, which specifies the resources will be relative to the HTML and not relative to any public path that's been set.
* Add override support for `context` option via `ILIB_CONTEXT` environment variable.
* Add override support for `create` option via `ILIB_ASSET_CREATE` environment variable.
> PLAT-115838: i18n ui tests fail with ui-test-utils 0.5.0

- CHANGELOG.md
- plugins/SnapshotPlugin/snapshot-helper.js
This PR fixes that iLib uses stale `ilib.data.cache` when an app built with snapshot option.
We are re-validating `window.localStorage` but not `ilib.data.cache` when we load an app built with sanpshot option.
So the "locale-less" stale ilib data cache remained.
Then, it leads to iLib to give no chance to retrieve the new locale info.
Added `ilib.clearCache()` call to clear the cache explicitly.
> PLAT-119858: Fixed SnapshotPlugin to clear ilib cache when updating environment

- plugins/VerboseLogPlugin/index.js
This PR fixes "enact pack --verbose" failed with below error.
`Chalk is not a constructor`
Chalk has deprecated `constructor` and introduced `Instance`. So we need to update it.
> PLAT-120195: Fixed enact pack --verbose to work

- CHANGELOG.md
- plugins/PrerenderPlugin/index.js
This PR fixes `enact pack --isomorphic` yields the wrong result.
Since https://github.com/jantimon/html-webpack-plugin/pull/1038 merged in `html-webpack-plugin`, the type of `js` assets from the plugin has been changed to an Array of strings.
To support this change, I fixed the wrong reference.
> PLAT-129892: Fixed PrerenderPlugin for compatibility to supporting latest `html-webpack-plugin`

- CHANGELOG.md
- plugins/PrerenderPlugin/index.js
- plugins/PrerenderPlugin/templates.js
- plugins/SnapshotPlugin/mock-window.js
This PR adds support for `ReactDOM.hydrate` instead of `ReactDOM.render` for prerendered apps.
React 17 deprecates using `ReactDOM.render` for hydrating a server-rendered container. So we need to use `ReactDOM.hydrate` instead.
This fix assumed that the app is rendering the app to the DOM which has id named "root".
I think it's quite safe since apps that using enact cli will have that DOM by default.
I'm not sure I can use `opts.chunk` for referencing "main.js" though.. but it works well.
> PLAT-123816: Add support for ReactDOM.hydrate instead of ReactDOM.render

- CHANGELOG.md
- mixins/framework.js
Build error founded when running ui tests, we've got "Module parse failed: Unexpected character '#' (1:0)" error.
Excluded `@enact/docs-utils` module in framework build content
PLAT-131686
> PLAT-131686: Fix build error founded when running ui tests

- CHANGELOG.md
- plugins/PrerenderPlugin/index.js
This PR fixes not injecting startup js when multiple locales exist.
The issue is reproducible from CLI 3.0.0. When `html-webpack-plugin` changed its tapable hooks, we adopted the changed one from 3.0.0, but we chose the wrong corresponding event for `html-webpack-plugin-after-html-processing`. The changed flow is described in https://github.com/jantimon/html-webpack-plugin#events.
> PLAT-139522: Fixed not injecting startup js when multiple locales exist

- CHANGELOG.md
- plugins/WebOSMetaPlugin/index.js
For setting the title, set an appropriate callback in dev-utils.
* `WebOSMetaPlugin`:
* added a parameter in WebOSMetaPlugin constructor
* removed the deprecated callback and replace the latest.
PLAT-139651
> PLAT-139651: Fixed not inserting title into the output HTML with enact pack

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
fix the below error
>Failed to compile
./home/taeyoung.hong/webos_build_server/WRN-10009/cli/node_modules/@enact/dev-utils/plugins/SnapshotPlugin/snapshot-helper.js
Cannot find module: 'fbjs/lib/ExecutionEnvironment'. Make sure this package is installed.
You can install this package by running: npm install fbjs/lib/ExecutionEnvironment.
Reason: 
"fbjs" was included in UI framework(moonstone/sandstone/...)
But the sandstone has been removed the "fbjs" module so the issue occurred now.
Add the fbjs module
WRN-12103
> WRN-12103: Fix snapshot build failure

- CHANGELOG.md
- option-parser.js
There's a needs to add additional paths to resolve modules for webpack.
Add `additionalModulePaths` in enact option.
This will be used in webpack config to allow the user to supply additional paths to the resolve.modules section.
WRN-14724
> WRN-14724: Add `additionalModuelPaths` to provide additional paths to resolve modules

- CHANGELOG.md
- mixins/isomorphic.js
- mixins/verbose.js
- npm-shrinkwrap.json
- option-parser.js
- package.json
- plugins/ILibPlugin/index.js
- plugins/PrerenderPlugin/index.js
- plugins/SnapshotPlugin/index.js
- plugins/VerboseLogPlugin/index.js
- plugins/WebOSMetaPlugin/index.js
- plugins/dll/EnactFrameworkRefPlugin.js
Migrated to webpack5
Updated APIs of plugins
Added #66 
Added `ILIB_ADDITIONAL_RESOURCES_PATH` as defined constants to resolve `process is undefined`
Verbose plugin needs to be fixed in WRN-19252
Warning related to Compliation.assets needs to be fixed in WRN-19249
WRN-18582
> WRN-18582: Migrate to webpack5

- .eslintrc.js
- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
`babel-eslint` has been deprecated
```
`babel-eslint` is now `@babel/eslint-parser`. This package will no longer receive updates.
```
Removed deprecated `babel-eslint`
When you release the new dev-utils version with this PR, you should update `npm-shrinkwrap.json`. 
> $ rm -rf npm-shrinkwrap.json
$ npm i
$ npm audit fix
$ npm shrinkwrap
WRN-12124
> WRN-12124: Remove deprecated babel-eslint module

- mixins/verbose.js
- npm-shrinkwrap.json
- package.json
- plugins/VerboseLogPlugin/index.js
In this PR, we'd like to fix enact pack --verbose is not working.
webpack's ProgressPlugin is changed to check if `compiler` is an instance of `Compiler`.
Currently, dev-utils and cli have different webpack modules so ProgressPlugin created from dev-utils cannot work correctly.
To remedy this, I've changed to create PrgressPlugin from cli's webpack module.
> WRN-19252: Fix VerboseLogPlugin is not working

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
- plugins/PrerenderPlugin/index.js
- plugins/PrerenderPlugin/templates.js
- plugins/SnapshotPlugin/index.js
- plugins/SnapshotPlugin/mock-window.js
- plugins/SnapshotPlugin/snapshot-helper.js
In this PR, we'd like to add support for React18.
React18 introduced `createRoot` and `hydrateRoot` instead of `render` and `hydrate`. And the exported pacakge changed from `react-dom` to `react-dom/client`.
The detailed information you could refer to is https://reactjs.org/blog/2022/03/29/react-v18.html.
> WRN-19694: Support for React18

- mixins/externals.js
- npm-shrinkwrap.json
- plugins/SnapshotPlugin/index.js
- plugins/dll/EnactFrameworkPlugin.js
- plugins/dll/EnactFrameworkRefPlugin.js
enact pack --framework and --externals are not working with webpack5
Fixed misusage of webOSMetaPlugin hooks
EnactFrameworkPlugin (enact pack --framework)
- DllModule.prototype.source is deprecated and should be replaced with DllModule.prototype.codeGeneration
- DllEntryPlugin now receives `option` object as the third parameter
- `entry` of `entryOption` hook now gives `enact.import` array instead of `enact`
- `Module.id` is deprecated and should use `ChunkGraph` API instead. (https://webpack.js.org/blog/2020-10-10-webpack-5-release/#module-and-chunk-graph)
EnactFrameworkRefPlugin (enact pack --externals)
- …
> WRN-20218: Fix eanct pack --framework and --externals options

- plugins/dll/EnactFrameworkRefPlugin.js
In this PR, we'd like to fix screenshot build fail from sandstone.
There are some miss delegated modules during that build.
- `call-bind/`: It has `/` at the end so we need to remove it.
- `readable-stream`: We don't have this in enact framework bundle so we should not delegate this lib.
I think we may have more miss delegated modules that we don't know yet.
But for now, we handled it all from in-house usage.
> WRN-20481: Fixed EnactFrameworkRefPlugin to resolve some miss delegated modules

- .eslintrc.js
- CHANGELOG.md
- mixins/externals.js
- mixins/isomorphic.js
- mixins/verbose.js
- npm-shrinkwrap.json
- option-parser.js
- package.json
- plugins/ILibPlugin/index.js
- plugins/PrerenderPlugin/index.js
- plugins/PrerenderPlugin/templates.js
- plugins/SnapshotPlugin/index.js
- plugins/SnapshotPlugin/mock-window.js
- plugins/SnapshotPlugin/snapshot-helper.js
- plugins/VerboseLogPlugin/index.js
- plugins/WebOSMetaPlugin/index.js
- plugins/dll/EnactFrameworkPlugin.js
- plugins/dll/EnactFrameworkRefPlugin.js
Merge feature/webpack5 branch to develop
Enact-DCO-1.0-Signed-off-by: Mikyung Kim ([mikyung27.kim@lge.com](mailto:mikyung27.kim@lge.com))
> WRO-231: Merge feature/webpack5 to develop

- CHANGELOG.md
- plugins/PrerenderPlugin/templates.js
`hydrateRoot(...): Target container is not a DOM element.` error shows when opening the app built with `--snapshot` option.
`hydrateRoot` changed the order of parameters. (https://reactjs.org/docs/react-dom-client.html#hydrateroot)
So I changed the order.
WRO-3697
> WRO-3697: Fix `hydrateRoot` related error after snapshot build

- CHANGELOG.md
- mixins/externals.js
- mixins/framework.js
- plugins/dll/EnactFrameworkRefPlugin.js
After migrating react18 from moonstone, ui test build is failing.
The main root cause of this issue was "moonstone" library was not built as "framework" when we build with enact pack --framework in moonstone root, whereas sandstone is. In the EnactFrameworkPlugin, we see "ThemeDecorator" for deciding whether the source needs to build as a framework or not but moonstone only has "MoonstoneDecorator" so it caused the issue.
After that was resolved, I saw `prop-types/node_modules/react-is/cjs/react-is.development` module is not found error. That module is in the framework source but with a different ID. It's a …
> WRO-3917: Fix moonstone ui test build fail

- CHANGELOG.md
- mixins/externals.js
- mixins/framework.js
- plugins/dll/EnactFrameworkRefPlugin.js
- plugins/dll/README.md
Since React18, `react-dom` has two sub-modules, `react-dom/client` and `react-dom/server`.
For building UI/SS test apps with `createRoot` API from `react-dom/client`, we need to expose them to the default framework bundle and reference them from apps that use the external enact framework.
Added `react-dom/client` and `react-dom/server` to the default framework and to reference as modules in the framework bundle
WRO-3919 …
> WRO-3919: Added `react-dom/client` and `react-dom/server` to the default framework bundle

- CHANGELOG.md
- option-parser.js
Previously, Enact CLI 4.x(includes webpack4) avoided fs-related build errors via using `nodeBuiltins` option.
https://v4.webpack.js.org/configuration/node/#other-node-core-libraries
But after CLI 5.x(includes webpack5), that option didn't work anymore.
https://webpack.js.org/configuration/node/#node
As per upgrading webpack v4->v5, node.fs: 'empty' option has been changed the other way.
https://webpack.js.org/migrate/5/#clean-up-configuration
For this reason, we added an additional option to avoid fs-related errors again. - `resolveFallback`
[//]: # (Are there any …
> WRO-4469: Added `resolveFallback` option

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
In current, the latest node version is 18, and the LTS version is 16(includes npm 8).
But we still use `lockfileVersion` 1 in npm-shrinkwrap.json created from npm 6.
For Node 16(LTS) or 18(Current) users, to prevent malfunctions of version asynchronous, need to update the version of the npm-shrinkwrap file to 2.
Update `lockfileVersion` of npm-shrinkwrap.json to v2
WRO-3879
Enact-DCO-1.0-Signed-off-by: Taeyoung Hong …
> WRO-3879: Update the version of npm-shrinkwrap file to v2

- CHANGELOG.md
- css-module-ident.js
We would like to add support for SCSS to Enact CLI
* Added `sass`, `scss` extension at fileIdentPattern in `css-module-ident` module.
WRO-630
> WRO-630: Add support for SCSS/Sass 

- CHANGELOG.md
- mixins/isomorphic.js
- plugins/PrerenderPlugin/index.js
- plugins/SnapshotPlugin/index.js
- plugins/SnapshotPlugin/mock-window.js
- plugins/SnapshotPlugin/snapshot-helper.js
- plugins/SnapshotPlugin/snapshot-redux-helper.js
`react-redux` does not update the state properly with snapshot building.
`react-redux` uses `useIsomorphicLayoutEffect` which is `useLayoutEffect` when the window object is available and `useEffect` when the window is unavailable, to attach store subscription callback.
Per `react-redux`, it needs `useLayoutEffect` to ensure the store subscription callback always has the selector from the latest render commit available. (Please refer to https://github.com/reduxjs/react-redux/blob/master/src/utils/useIsomorphicLayoutEffect.ts)
But when we run snapshot building, there is no window object so it is "snapshotted" …
> WRO-5782: SnapshotPlugin: Fixed `react-redux` not updating state

- mixins/verbose.js
- plugins/VerboseLogPlugin/index.js
We found that we could access to "ProgressPlugin" component through "compiler.webpack.ProgressPlugin", instead of passing "ProgressPlugin" from CLI as we did in #91.
In this PR, we revert #91 and use dev-utils' ProgressPlugin itself.
- Remove passing "ProgressPlugin" from CLI
- Use "compiler.webpack.ProgressPlugin" from VerbosePlugin in dev-utils
WRO-7036
> WRO-7036: Fix to use `compiler.webpack.ProgressPlugin` from `VerboseLogPlugin`

- plugins/GracefulFsPlugin/index.js
- plugins/ILibPlugin/index.js
- plugins/PrerenderPlugin/index.js
- plugins/WebOSMetaPlugin/index.js
When building or serving apps below deprecation warnings are showing:
```
(node:21292) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
```
In this PR, we'd like to remove this warning message.
Some of our plugins are modifying `Compilation.assets` directly to add assets while …
> WRO-748: Fix Plugins to use `processAssets` hook to remove deprecation warning while building apps

- CHANGELOG.md
- plugins/PrerenderPlugin/index.js
Fixed the incorrect behavior found in the automation test.
Locales no longer exist under @enact/i18n after Enact v3.0.0 and are located in the iLib module.
For the "--locales=all" option to work correctly, the directory of the locales must be redirected.
Redirect the directory from @enact/i18n to ilib.
WRO-4973
> WRO-4973: Fix wrong ilib path when locales option is 'all'

- CHANGELOG.md
- plugins/WebOSMetaPlugin/index.js
After html-webpack-plugin v5, the plugin is no longer inserting title via modifying `plugin.options.title` on `beforeAssetTagGeneration` hook.
Insert title tag to `htmlPluginData.headTags` in `afterTemplateExecution` hook.
WRO-12406
> WRO-12406: Fixed not inserting title into the output HTML

- CHANGELOG.md
- plugins/ILibPlugin/index.js
When `publicPath` is given, `enact pack` fails since `ILibPLubin` throws unexpected paths.
For example, if `publicPath` is `/`, ilib.resolved is /"node_modules/ilib" instead of "/node_modules/ilib"
Fixed to join the `publicPath` with `path.join`
WRO-10697
> WRO-10697: Fixed `ILibPlugin` to resolve ilib and resources paths properly when `publicPath` is given

- npm-shrinkwrap.json
- package.json
For preventing malware issues, we need to update node modules that fix severity vulnerabilities.
Update node modules' minor version to fix severity vulnerabilities.
Pinning eslint-plugin-react to v7.31.11 (reason: WRP-6801)
WRP-4410
> WRP-4410: Fix security vulnerabilities

- CHANGELOG.md
- mixins/verbose.js
- npm-shrinkwrap.json
- package.json
- plugins/PrerenderPlugin/index.js
- plugins/PrerenderPlugin/vdom-server-render.js
- plugins/SnapshotPlugin/index.js
- plugins/VerboseLogPlugin/index.js
`chalk` v5 and `find-cache-dir` v4 have been released.
Those modules need to be updated to the latest node modules to fix security vulnerabilities and prevent malware.
Update `chalk` v5 and `find-cache-dir` v4
- `chalk` and `find-cache-dir` are now pure ESM. Please [read this](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c).
`chalk`: https://github.com/chalk/chalk/releases/tag/v5.0.0
`find-cache-dir`: …
> WRP-14327: Update chalk v5 and find-cache-dir v4

- CHANGELOG.md
- mixins/verbose.js
- plugins/VerboseLogPlugin/index.js
'enact pack --verbose' option not works
Reason: Importing "chalk" outside of the "VerboseLogPlugin" causes timing issues, so the verbose log not working.
https://github.com/enactjs/dev-utils/blob/833e42433eca1b6847475ee2c5f415231054fc4a/mixins/verbose.js#L9-L17
- Importing "chalk" inside of the "VerboseLogPlugin"
- If "chalk" has not been imported yet, call update() recursively.
- The `enabled` option was deprecated in the' chalk' module.
So it migrated to `level`. …
> WRP-25031: Fix 'enact pack --verbose' option not works

- CHANGELOG.md
- config-helper.js
- option-parser.js
To improve the performance of your hosted web app, the size of main.js should be reduced. 
Improve the execution time of your app by splitting the main.js file via webpack config settings.
- Add `replaceEntry` function in `config-helper.js` to add multiple entries.
- Add `entry` config in `option-parser.js`. 
- HOW TO USE
```javascript
...
"enact": {
...
"entry": {
// files that need to split
"MainPanel": "./src/views/MainPanel.js",
"MainPanel2": "./src/views/MainPanel2.js",
"main": "./src/index.js",
"MyPanel": "./src/views/MyPanel.js",
"Editable": "./src/views/Editable.js"
}
},
...
``` 
Purpose of Code …
> WRR-1076: Add replaceEntry function in config-helper.js to support code splitting

- CHANGELOG.md
- plugins/PrerenderPlugin/locales-tv.json
CLI should make an HTML file with ko-TW to support "ko-US".
But this locale is not included in the locale-map.json.
Updated PrerenderPlugin's locales-tv.json with the 2025 country language list.
WRR-24257
> WRR-24257: Updated locales-tv.json with the 2025 language list
